version: '3.8'

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://admin:admin@mongo:27017/admin
    depends_on:
      - mongo
    networks:
      - backend

volumes:
  mongodb-data:

networks:
  backend:
    driver: bridge